### ISSUE TITLE
profiling runtime CompassApps

### ISSUE THREAD

**Issue by robfitzgerald** [NREL/routee-compass#112]
in order to better understand non-linear memory performance wrt very large inputs, we need to explore different memory profiling options, with both system-level and module-level observations.

### module-level

a few things need to be observed at the module level, using the Allocative crate:

- rust Allocative crate for inspecting runtime growth in search at the row-level
  - HashMap<VertexId, SearchAppResult> 
    - write size estimate to output row, perhaps in summary output plugin

- Allocative: the size of the CompassApp run_result object after the end of a run
  - should we make output plugins operate on a `&'a mut serde_json::Value`?
  - ...at least get rid of the Vec allocations!

### system-level

while this doesn't necessarily have any code changes, we want to see a plot of memory over time of a national compass run in order to get a view into memory at different app phases:

  - the CompassApp instance is fully built
  - input queries (raw)
  - input queries (post-input plugins)
  - searches are running
  - end of batch (size of "memory leak" or unnecessary allocations)

### other profiling details

- use samply crate for CPU profiling, put on sherlock holmes hat and dig around
- report number of iterations from search result to output row

**Comment by nreinicke** [comment]
Just tagging here that I've continued work on implementing the Allocative trait for some more internal data structures like `SearchAppResult` and will share findings as I get them.

**Comment by robfitzgerald** [comment]
saaaaweeeeet! can't wait to see what else you dig up. i'm at B16 today, where i hope to catch up on all things work, post-sick-baby.

**Comment by nreinicke** [comment]
Okay here are some initial results. I ran the national graph over 10 batches of 40 random national queries using [this config](https://github.nrel.gov/MBAP/routee-compass-tomtom/blob/ndr/performance-benchmarks/compass_tomtom_national_energy_interpolate.toml). Note that I didn't load the traversal plugin so no geometry in the results and I only used road classes 1-5. 

Here's a look at the memory usage over time:

![image](https://github.com/NREL/routee-compass/assets/1743744/4deaa302-4aef-4534-892a-e123d856f34d)

The initial jump shows the app being loaded into memory, taking up around 70G (I haven't yet looked into the breakdown of memory there like how much is graph how much is edge rtree, etc) and then levels off as the app runs. This gives me some confidence that we're not leaking memory anywhere (at least in this case)

Then, I tracked the size in memory of each `SearchAppResult`:

![image](https://github.com/NREL/routee-compass/assets/1743744/0991d2b9-2be1-4ae3-8513-909b9fcba657)

Some of these results can get pretty big around 2GB which could limit the level of parallelism for a national run.

Finally, I profiled the memory usage of data stores that make up the a star search algo:

```rust
    let mut costs: InternalPriorityQueue<VertexId, ReverseCost> =
        InternalPriorityQueue(PriorityQueue::new());
    let mut frontier: HashMap<VertexId, AStarFrontier> = HashMap::new();
    let mut traversal_costs: HashMap<VertexId, Cost> = HashMap::new();
    let mut solution: HashMap<VertexId, SearchTreeBranch> = HashMap::new();
```

I did this at the _end_ of the algorithm so no insight into how big the costs queue gets but here it is:

![image](https://github.com/NREL/routee-compass/assets/1743744/1ea314e0-e200-4ecd-9189-75b28b7ffcd4)

The left most block is the frontier, the middle block is the solution and the right block is the traversal_costs. Something that stands out immediately to me is that we're duplicating the traversal state for the solution and the frontier. Another thing is that there is some extra space in our traversal state vectors that is unused.

So, leading to some ideas for memory improvement:

 - Perhaps we could make the `tree` argument on the search app result optional if the user doesn't plan to do anything with it, droping it from memory as soon as the algorithm finishes. 
 - If we could find a way to share the traversal state (maybe lifetimes) between the solution and the frontier we could cut "in search" memory significantly.
 - We should definitely size our traversal state vectors to be exactly the size of how many state variables will fit into it.

**Comment by robfitzgerald** [comment]
awesome. Jake and I just read through this. while you're talking about ways to improve memory, we were talking about how this is a great guideline on memory requirements for today, that long routes need up to 2GB of RAM, but most typical routes need < 500MB, and that can be a rule of thumb for now on how to choose parallelism for a batch. like, if you have pre-partioned queries into long and not long distance routes, and you have 100GB RAM, you could choose a parallelism of 15 for the long and 60 for the short to fit the remaining memory (not that you'd want to fit it _exactly_ but you know what i mean).

great stuff, totally actionable information here. an idea for another profiling run: seeing you did _random_ queries. maybe we should see the memory requirements for a few outliers, like Seattle > Key West, to try and estimate an upper bound. since RAM requirements are non-linear wrt inputs, we may see it hop up beyond 2GB, and that could be informative. 

IN FACT: this makes me want a scatterplot from haversine weight to tree memory. if we run a polynomial regression over that dataset, we could end up with a function that we could use programmatically for assigning parallelism + partitioning schemes.

love your ideas! thanks Nick!

**Comment by robfitzgerald** [comment]
coming back around to these ideas:

- Perhaps we could make the tree argument on the search app result optional if the user doesn't plan to do anything with it, droping it from memory as soon as the algorithm finishes.
- If we could find a way to share the traversal state (maybe lifetimes) between the solution and the frontier we could cut "in search" memory significantly.
- We should definitely size our traversal state vectors to be exactly the size of how many state variables will fit into it.

**Comment by robfitzgerald** [comment]
coming back around to these ideas:

> Perhaps we could make the tree argument on the search app result optional if the user doesn't plan to do anything with it, dropping it from memory as soon as the algorithm finishes

i like this but i also wonder if there's a more obvious way to do this that doesn't make us uncertain if there's a tree for a given result. like, we know that we need that tree to exist at least until we create a route from it. maybe there's a way to better model the phases of output processing so that it's less ambiguous whether there is a tree still or not.

> If we could find a way to share the traversal state (maybe lifetimes) between the solution and the frontier we could cut "in search" memory significantly

right, this is coming up as i'm exploring the AccessModel idea as well. an abstraction that manages allocation/cloning, inspection and updates of traversal states would be a part of this.

> We should definitely size our traversal state vectors to be exactly the size of how many state variables will fit into it

totally.

maybe we need to define a performance sprint and create some tasks from these ideas. and here are a few more to tack on here so i don't forget.

- output plugins applied to `& mut serde_json::Value`, return `Result<(), Error>`
- streaming queries from file instead of loading all at once
- a way use estimated trip distance to partition queries into batches that run with different degrees of parallelism

**Comment by robfitzgerald** [comment]
revisiting this again, noting the first plot, the memory use by step plot ([above](https://github.com/NREL/routee-compass/issues/112#issuecomment-1932574516)):

that "plateau" may be an inaccurate read on memory usage, since the config is only using the summary output plugin. so, at the beginning of each batch, the inputs are small JSONs, and at the end of each batch, they are small JSONs again. i think the "real" total RAM line would fluctuate a whole lot more between those sample points. not that i'm asking you to figure out how to sample that, but, i think we should keep it in mind (though your original hypothesis still smells right too, that there doesn't seem to be a memory leak-ish thing going on).

**Comment by nreinicke** [comment]
> i think the "real" total RAM line would fluctuate a whole lot more between those sample points. 

yeah that's a good point since we're not seeing the memory that the processes using during the search; that would definitely be a good next step but at least it points to the fact that the memory isn't being leaked.

**Comment by nreinicke** [comment]
Closing this and noting that we've done significant work to improve the performance and reduce the memory overhead. It wouldn't hurt to revisit this sometime in the future but for now the application is performant enough to do some national level analysis.
