### ISSUE TITLE
Managing life of tree object in search result

### ISSUE THREAD

**Issue by robfitzgerald** [NREL/routee-compass#114]
The phases of a search for a query are like this:
  1. **search**: we spend the whole search building the tree, which is (probably) the majority of the tree's lifetime
  2. **output plugin**: we hold on to the tree for the whole duration of applying output plugins in case a plugin requires it

But a tree size grows non-linearly wrt distance, as we see below (stolen from [here](https://github.com/NREL/routee-compass/issues/112#issuecomment-1932574516)):

![image](https://github.com/NREL/routee-compass/assets/7003022/b04a864f-0f9f-49c2-98a7-71f1e728962f)

while we cannot reduce memory usage in phase 1 and should assume each process has a maximum memory requirement that suits the largest expected tree size, we could break the output plugin processing into two phases, one with the tree and one where the tree is discarded, in order to reduce the lifetime of the tree and therefore remove some memory pressure in the system.

**Comment by robfitzgerald** [comment]
While writing this, i was starting to wonder if this actually does solve a problem, since we will need to build the full tree regardless. so, from a capacity standpoint, we always want to grant each process at least enough memory space for the full tree. so, what good does it do to remove it prematurely, if that is already the assumption?

**Comment by nreinicke** [comment]
> so, what good does it do to remove it prematurely, if that is already the assumption?

yeah that's a really good point... probably fine to just keep it as is...

**Comment by nreinicke** [comment]
Closing as we decided this doesn't make sense as an optimization since we already need to build the full tree.
