### ISSUE TITLE
smarter parallel scheduling based on weight estimates

### ISSUE THREAD

**Issue by robfitzgerald** [NREL/routee-compass#118]
As discussed [here](https://github.com/NREL/routee-compass/issues/112#issuecomment-1932574516), we observed that there is a non-linear relationship between some requests and their runtimes, as expected. This is likely the relationship between the distance of the search and the size of the search space:

![image](https://private-user-images.githubusercontent.com/1743744/303085289-0991d2b9-2be1-4ae3-8513-909b9fcba657.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDczNDMyMDEsIm5iZiI6MTcwNzM0MjkwMSwicGF0aCI6Ii8xNzQzNzQ0LzMwMzA4NTI4OS0wOTkxZDJiOS0yYmUxLTRhZTMtODUxMy05MDliOWZjYmE2NTcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMDdUMjE1NTAxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODhkZjY0MDliYTFmYzU3MDZiM2E4NWU2NDg1M2YxNWM1MmYxMWExMDU5ZGY1ZWQ1NTBmNDAzNzhiNDIzMzhkOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.7yODsFDnoyHRSutkUMDNzWD51pLGCossgu8CV2Wa9bg)

If we plot an exponential line against the graph, we end up with a mathematical way to describe that relationship. If this can be expressed as a function of the number of edges in the Graph, then we can generalize it. A user could then pick x-axis values from the above graph as boundary values, creating "bins." we can batch queries that fall in the same "bin" and map it to some parallelism argument that essentially automates resource management of the CPU and RAM space. this is aided by runtime memory profiling estimates which can be used to programmatically find the correct processes-per-bin values.

**Comment by nreinicke** [comment]
Just ran a national run using the latest changes on main and got these relationships between route distance and search runtime and search result size:

### runtime
![image](https://github.com/NREL/routee-compass/assets/1743744/1a5f01e7-2254-4197-8de2-06b07cd55b43)

### search result size
![image](https://github.com/NREL/routee-compass/assets/1743744/a71d3f0a-5712-4309-906c-f14685db9c27)

**Comment by robfitzgerald** [comment]
this was added a while ago via the LoadBalancerInputPlugin
