### ISSUE TITLE
Support batch runs

### ISSUE THREAD

**Issue by nreinicke** [NREL/routee-compass#17]
When running a large amount of queries to one call of `CompassApp.run()` it would be nice to optionally batch the queries and periodically write the results to a file rather than holding them in memory.

**Comment by nreinicke** [comment]
There are a couple of ways we could implement this.

We could expose a new function on the compass app that would split the queries into batches and then write them to an output file, something like:

```python
def run_batch(self, queries, output_file: Path, batch_size: Optional[int]):
   # compute batches

   for batch in batches:
    batch_result = self.run(batch)
    # write batch_result to file
```

Or, we could implement this functionality in rust and pass the output_file and batch_size parameters there.

I'm thinking it makes more sense to implement this in our python wrapper.

**Comment by nreinicke** [comment]
Thinking about this a bit more, the python implementation would be easier but it wouldn't be guaranteed to run the queries in the specified batch since since it's possible for the grid search plugin (or any other plugin) to generate multiple queries from a single query. Perhaps this is good justification to implement batching on the rust side?

**Comment by nreinicke** [comment]
Continued discussion in #19

**Comment by robfitzgerald** [comment]
hey, sorry i missed/duplicated this issue!
