### ISSUE TITLE
Pass optional folium map to plot

### ISSUE THREAD

**Issue by nreinicke** [NREL/routee-compass#199]
Similar to the [`plot_route_folium`](https://github.com/NREL/routee-compass/blob/fb8376760a7cd4447db71fcc40b193cb0efbcacb/python/nrel/routee/compass/plot/plot_folium.py#L16) function where we can pass an optional pre-existing folium map, we should also allow a user to pass a folium map the the [`plot_routes_folium`](https://github.com/NREL/routee-compass/blob/fb8376760a7cd4447db71fcc40b193cb0efbcacb/python/nrel/routee/compass/plot/plot_folium.py#L122) function so it can be customized before plotting the routes on it

**Comment by vbmendes** [comment]
I will work on this issue.
