### ISSUE TITLE
Build out additional example notebooks

### ISSUE THREAD

**Issue by nreinicke** [NREL/routee-compass#212]
In addition to the [open street maps example](https://github.com/NREL/routee-compass/blob/main/docs/notebooks/open_street_maps_example.ipynb), we could build out several more interesting example notebooks. Here are some ideas. Please comment here on this issue if you want to build out one of these or if you have an idea for another example.

 - Analyze a route (or multiple routes) in detail, looking at areas that result in high (or low) energy consumption
 - Use grid search to do a large sweep (for example, run a sweep of time and energy weights between 0 and 1 at 0.01 increments and observe the routes and route traversal summaries)
 - Explore a search tree in detail

**Comment by robfitzgerald** [comment]
As discussed on slack, a possible stretch goal here is a notebook that demonstrates the dynamic model loading via combinations of query time arguments and config plugins.
