### ISSUE TITLE
Enable adding grade via google API

### ISSUE THREAD

**Issue by nreinicke** [NREL/routee-compass#213]
Our current workflow for adding grade to the graph is to download USGS raster elevation tiles and then add them to the osmnx graph using the [`add_node_elevations_raster`](https://github.com/NREL/routee-compass/blob/4a764088d0372a08596c274ed90f4bf4b884dad7/python/nrel/routee/compass/io/utils.py#L169) function. osmnx also support the [google maps elevation api ](https://osmnx.readthedocs.io/en/stable/user-reference.html#osmnx.elevation.add_node_elevations_google)and so we could add an additional pathway for our users who have an API key to google maps to use that functionality as well.

**Comment by zenon18** [comment]
zenon18 (Mark W.) will like to do this issue
