### ISSUE TITLE
Energy traversal service gets cloned 

### ISSUE THREAD

**Issue by robfitzgerald** [NREL/routee-compass#34]
speed_grade_energy_model_builder.rs has a service defined inline with the builder; in total, the chain looks like this:

SpeedGradeEnergyModelBuilder (1)
  |
SpeedGradeModelService (2)
  |
SpeedGradeEnergyModelService (3)
  |
SpeedGradeModel (4)

there's an extra layer there. in the process, we end up cloning SpeedGradeModelService (2) each time we build the SpeedGradeModel, which now means cloning the hashmap of prediction models (cloning the speed lookup table is ok, that is cloning an `Arc`).

the cloning is likely leading to longer runtimes as each query creates a clone. this should be rewritten so that no cloning is needed.

**Comment by robfitzgerald** [comment]
i think our problem here is that we in fact do need 4 layers to a traversal model:
1. **builder** at the top, an empty struct, builds a service
2. **engine** loaded once, may have heavyweight dependencies, tables, prediction models, whatever
3. **service** holds a persistent `Arc<Engine>` and builds a model by cloning the engine
4. **model** implements `TraversalModel` and holds an `Arc<Engine>` that lasts the duration of a search query

whatever we name (2), i think we actually need this much. a **builder** lives only at the top of the application and is stateless. a **service** lives as long as the application after initialization with the `CompassApp` holding a reference to it, but there is some final delayed initialization that comes from calling build on the service which gives us a model. it's function is to keep a reference to the persistent object with the heavyweight dependencies and then provide a method for the final `build` phase. so, maybe that sets it apart from being an **engine**, which is that object with heavyweight dependencies.

**Comment by nreinicke** [comment]
Yeah this brings up a good point. Could we just let the traversal model handle the details with respect to dealing with the heavyweight assets? The `TraversalModel` trait could require a new method, `initialize_from_query` or something that takes a json query and then returns a clone of itself in which it modifies the cheap things (like energy cost coefficient) and does an inexpensive arc clone of the large items (like speed tables and prediction model hashmaps). Then, we would just need a builder and a traversal model which might cut down on the complexity a bit.

**Comment by robfitzgerald** [comment]
> Could we just let the traversal model handle the details with respect to dealing with the heavyweight assets?

but what is the type that results from `initialize_from_query`? either it is _different_ than whatever it's being called on, because it's possible we will scrape some details off the query and append it to the persistent object. or, we need to add a bunch of _optional_ fields, by default set to `None` that will be replaced later. but that has a code smell to me, like it's mimicking OO in FP.

```rust

struct MyTraversalModelService

struct MyTraversalModel {
  service: Arc<MyTraversalModelService>,
  energy_coef: Option<f64>
}

impl MyTraversalModel {
  fn initialize_from_query() -> Result<MyTraversalModel, Error> {
    // sets the `Option<f64>` to `Some(value)` here
  }
}
```

ah, here: if we want to know if a TraversalModel like this is fully prepped for a query, we have to inspect all of it's fields. we actually need to know a lot about the implementation, in case some fields can be left optional. but, if we separate TraversalModel from the persistent "engine-y" bit, we always know that, if we have a TraversalModel, it has been fully initialized.

**Comment by nreinicke** [comment]
> if we separate TraversalModel from the persistent "engine-y" bit, we always know that, if we have a TraversalModel, it has been fully initialized.

yeah that makes sense and is good justification for separating them.
