### ISSUE TITLE
Use ONNX vehicle models for default library

### ISSUE THREAD

**Issue by nreinicke** [NREL/routee-compass#67]
Now that we support ONNX models by default, we can update our [default model library](https://github.com/NREL/routee-compass/tree/main/python/nrel/routee/compass/resources/models) to use onnx based models rather than the slower smartcore random forest models.

**Comment by nreinicke** [comment]
Hmm, after doing a test run on the national beer run, the smartcore based queries are taking about 3 minutes to run whereas the onnx based queries are taking closer to 26 minutes to run. Clearly, the onnx models are much slower at this level and so perhaps we shouldn't consider them for our default models. It could be worth profiling the onnx based models to check to make sure something silly isn't happening.

**Comment by robfitzgerald** [comment]
Onnx performance issues led to keeping smartcore as the default over onnx
